// Generated by gencpp from file car_srv/Car.msg
// DO NOT EDIT!


#ifndef CAR_SRV_MESSAGE_CAR_H
#define CAR_SRV_MESSAGE_CAR_H

#include <ros/service_traits.h>



#include <car_srv/CarRequest.h>
#include <car_srv/CarResponse.h>


namespace car_srv
{

struct Car
{

typedef CarRequest Request;
typedef CarResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Car
} // namespace car_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car_srv::Car > {
  static const char* value()
  {
    return "54ccab5727cf288228188cbb99fe7680";
  }

  static const char* value(const ::car_srv::Car&) { return value(); }
};

template<>
struct DataType< ::car_srv::Car > {
  static const char* value()
  {
    return "car_srv/Car";
  }

  static const char* value(const ::car_srv::Car&) { return value(); }
};


// service_traits::MD5Sum< ::car_srv::CarRequest> should match
// service_traits::MD5Sum< ::car_srv::Car >
template<>
struct MD5Sum< ::car_srv::CarRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car_srv::Car >::value();
  }
  static const char* value(const ::car_srv::CarRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_srv::CarRequest> should match
// service_traits::DataType< ::car_srv::Car >
template<>
struct DataType< ::car_srv::CarRequest>
{
  static const char* value()
  {
    return DataType< ::car_srv::Car >::value();
  }
  static const char* value(const ::car_srv::CarRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car_srv::CarResponse> should match
// service_traits::MD5Sum< ::car_srv::Car >
template<>
struct MD5Sum< ::car_srv::CarResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car_srv::Car >::value();
  }
  static const char* value(const ::car_srv::CarResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car_srv::CarResponse> should match
// service_traits::DataType< ::car_srv::Car >
template<>
struct DataType< ::car_srv::CarResponse>
{
  static const char* value()
  {
    return DataType< ::car_srv::Car >::value();
  }
  static const char* value(const ::car_srv::CarResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_SRV_MESSAGE_CAR_H
