// Generated by gencpp from file car_srv/CarRequest.msg
// DO NOT EDIT!


#ifndef CAR_SRV_MESSAGE_CARREQUEST_H
#define CAR_SRV_MESSAGE_CARREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_srv
{
template <class ContainerAllocator>
struct CarRequest_
{
  typedef CarRequest_<ContainerAllocator> Type;

  CarRequest_()
    : range(0.0)  {
    }
  CarRequest_(const ContainerAllocator& _alloc)
    : range(0.0)  {
  (void)_alloc;
    }



   typedef float _range_type;
  _range_type range;





  typedef boost::shared_ptr< ::car_srv::CarRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_srv::CarRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CarRequest_

typedef ::car_srv::CarRequest_<std::allocator<void> > CarRequest;

typedef boost::shared_ptr< ::car_srv::CarRequest > CarRequestPtr;
typedef boost::shared_ptr< ::car_srv::CarRequest const> CarRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_srv::CarRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_srv::CarRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_srv::CarRequest_<ContainerAllocator1> & lhs, const ::car_srv::CarRequest_<ContainerAllocator2> & rhs)
{
  return lhs.range == rhs.range;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_srv::CarRequest_<ContainerAllocator1> & lhs, const ::car_srv::CarRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_srv::CarRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_srv::CarRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_srv::CarRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_srv::CarRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_srv::CarRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_srv::CarRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_srv::CarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2a7c9ed52e86fcc9ff2372cd521ad59";
  }

  static const char* value(const ::car_srv::CarRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2a7c9ed52e86fccULL;
  static const uint64_t static_value2 = 0x9ff2372cd521ad59ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_srv::CarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_srv/CarRequest";
  }

  static const char* value(const ::car_srv::CarRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_srv::CarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 range\n"
;
  }

  static const char* value(const ::car_srv::CarRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_srv::CarRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.range);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_srv::CarRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_srv::CarRequest_<ContainerAllocator>& v)
  {
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_SRV_MESSAGE_CARREQUEST_H
