// Generated by gencpp from file car_srv/CarResponse.msg
// DO NOT EDIT!


#ifndef CAR_SRV_MESSAGE_CARRESPONSE_H
#define CAR_SRV_MESSAGE_CARRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_srv
{
template <class ContainerAllocator>
struct CarResponse_
{
  typedef CarResponse_<ContainerAllocator> Type;

  CarResponse_()
    : direction()  {
    }
  CarResponse_(const ContainerAllocator& _alloc)
    : direction(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::car_srv::CarResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_srv::CarResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CarResponse_

typedef ::car_srv::CarResponse_<std::allocator<void> > CarResponse;

typedef boost::shared_ptr< ::car_srv::CarResponse > CarResponsePtr;
typedef boost::shared_ptr< ::car_srv::CarResponse const> CarResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_srv::CarResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_srv::CarResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_srv::CarResponse_<ContainerAllocator1> & lhs, const ::car_srv::CarResponse_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_srv::CarResponse_<ContainerAllocator1> & lhs, const ::car_srv::CarResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car_srv::CarResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_srv::CarResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_srv::CarResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_srv::CarResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_srv::CarResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_srv::CarResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_srv::CarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "326e9417def5db9a05a2704a4d8de15e";
  }

  static const char* value(const ::car_srv::CarResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x326e9417def5db9aULL;
  static const uint64_t static_value2 = 0x05a2704a4d8de15eULL;
};

template<class ContainerAllocator>
struct DataType< ::car_srv::CarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_srv/CarResponse";
  }

  static const char* value(const ::car_srv::CarResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_srv::CarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string direction\n"
;
  }

  static const char* value(const ::car_srv::CarResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_srv::CarResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_srv::CarResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_srv::CarResponse_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_SRV_MESSAGE_CARRESPONSE_H
