// Generated by gencpp from file srv_custom/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SRV_CUSTOM_MESSAGE_ADDTWOINTS_H
#define SRV_CUSTOM_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <srv_custom/AddTwoIntsRequest.h>
#include <srv_custom/AddTwoIntsResponse.h>


namespace srv_custom
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace srv_custom


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_custom::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::srv_custom::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::srv_custom::AddTwoInts > {
  static const char* value()
  {
    return "srv_custom/AddTwoInts";
  }

  static const char* value(const ::srv_custom::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::srv_custom::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::srv_custom::AddTwoInts >
template<>
struct MD5Sum< ::srv_custom::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv_custom::AddTwoInts >::value();
  }
  static const char* value(const ::srv_custom::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_custom::AddTwoIntsRequest> should match
// service_traits::DataType< ::srv_custom::AddTwoInts >
template<>
struct DataType< ::srv_custom::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::srv_custom::AddTwoInts >::value();
  }
  static const char* value(const ::srv_custom::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_custom::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::srv_custom::AddTwoInts >
template<>
struct MD5Sum< ::srv_custom::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv_custom::AddTwoInts >::value();
  }
  static const char* value(const ::srv_custom::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_custom::AddTwoIntsResponse> should match
// service_traits::DataType< ::srv_custom::AddTwoInts >
template<>
struct DataType< ::srv_custom::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::srv_custom::AddTwoInts >::value();
  }
  static const char* value(const ::srv_custom::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_CUSTOM_MESSAGE_ADDTWOINTS_H
