// Generated by gencpp from file srv_custom/customsrv.msg
// DO NOT EDIT!


#ifndef SRV_CUSTOM_MESSAGE_CUSTOMSRV_H
#define SRV_CUSTOM_MESSAGE_CUSTOMSRV_H

#include <ros/service_traits.h>


#include <srv_custom/customsrvRequest.h>
#include <srv_custom/customsrvResponse.h>


namespace srv_custom
{

struct customsrv
{

typedef customsrvRequest Request;
typedef customsrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct customsrv
} // namespace srv_custom


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_custom::customsrv > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::srv_custom::customsrv&) { return value(); }
};

template<>
struct DataType< ::srv_custom::customsrv > {
  static const char* value()
  {
    return "srv_custom/customsrv";
  }

  static const char* value(const ::srv_custom::customsrv&) { return value(); }
};


// service_traits::MD5Sum< ::srv_custom::customsrvRequest> should match
// service_traits::MD5Sum< ::srv_custom::customsrv >
template<>
struct MD5Sum< ::srv_custom::customsrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv_custom::customsrv >::value();
  }
  static const char* value(const ::srv_custom::customsrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_custom::customsrvRequest> should match
// service_traits::DataType< ::srv_custom::customsrv >
template<>
struct DataType< ::srv_custom::customsrvRequest>
{
  static const char* value()
  {
    return DataType< ::srv_custom::customsrv >::value();
  }
  static const char* value(const ::srv_custom::customsrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_custom::customsrvResponse> should match
// service_traits::MD5Sum< ::srv_custom::customsrv >
template<>
struct MD5Sum< ::srv_custom::customsrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv_custom::customsrv >::value();
  }
  static const char* value(const ::srv_custom::customsrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_custom::customsrvResponse> should match
// service_traits::DataType< ::srv_custom::customsrv >
template<>
struct DataType< ::srv_custom::customsrvResponse>
{
  static const char* value()
  {
    return DataType< ::srv_custom::customsrv >::value();
  }
  static const char* value(const ::srv_custom::customsrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_CUSTOM_MESSAGE_CUSTOMSRV_H
