// Generated by gencpp from file srv_custom/customsrvResponse.msg
// DO NOT EDIT!


#ifndef SRV_CUSTOM_MESSAGE_CUSTOMSRVRESPONSE_H
#define SRV_CUSTOM_MESSAGE_CUSTOMSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv_custom
{
template <class ContainerAllocator>
struct customsrvResponse_
{
  typedef customsrvResponse_<ContainerAllocator> Type;

  customsrvResponse_()
    : sum(0)  {
    }
  customsrvResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::srv_custom::customsrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv_custom::customsrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct customsrvResponse_

typedef ::srv_custom::customsrvResponse_<std::allocator<void> > customsrvResponse;

typedef boost::shared_ptr< ::srv_custom::customsrvResponse > customsrvResponsePtr;
typedef boost::shared_ptr< ::srv_custom::customsrvResponse const> customsrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv_custom::customsrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv_custom::customsrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srv_custom::customsrvResponse_<ContainerAllocator1> & lhs, const ::srv_custom::customsrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srv_custom::customsrvResponse_<ContainerAllocator1> & lhs, const ::srv_custom::customsrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srv_custom

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srv_custom::customsrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv_custom::customsrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_custom::customsrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_custom::customsrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_custom::customsrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_custom::customsrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv_custom::customsrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::srv_custom::customsrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::srv_custom::customsrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv_custom/customsrvResponse";
  }

  static const char* value(const ::srv_custom::customsrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv_custom::customsrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
;
  }

  static const char* value(const ::srv_custom::customsrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv_custom::customsrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct customsrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv_custom::customsrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv_custom::customsrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_CUSTOM_MESSAGE_CUSTOMSRVRESPONSE_H
