// Generated by gencpp from file srv_custom/customsrvRequest.msg
// DO NOT EDIT!


#ifndef SRV_CUSTOM_MESSAGE_CUSTOMSRVREQUEST_H
#define SRV_CUSTOM_MESSAGE_CUSTOMSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv_custom
{
template <class ContainerAllocator>
struct customsrvRequest_
{
  typedef customsrvRequest_<ContainerAllocator> Type;

  customsrvRequest_()
    : a(0)
    , b(0)  {
    }
  customsrvRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::srv_custom::customsrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv_custom::customsrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct customsrvRequest_

typedef ::srv_custom::customsrvRequest_<std::allocator<void> > customsrvRequest;

typedef boost::shared_ptr< ::srv_custom::customsrvRequest > customsrvRequestPtr;
typedef boost::shared_ptr< ::srv_custom::customsrvRequest const> customsrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv_custom::customsrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv_custom::customsrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srv_custom::customsrvRequest_<ContainerAllocator1> & lhs, const ::srv_custom::customsrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srv_custom::customsrvRequest_<ContainerAllocator1> & lhs, const ::srv_custom::customsrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srv_custom

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srv_custom::customsrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv_custom::customsrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_custom::customsrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_custom::customsrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_custom::customsrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_custom::customsrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv_custom::customsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::srv_custom::customsrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::srv_custom::customsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv_custom/customsrvRequest";
  }

  static const char* value(const ::srv_custom::customsrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv_custom::customsrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::srv_custom::customsrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv_custom::customsrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct customsrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv_custom::customsrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv_custom::customsrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_CUSTOM_MESSAGE_CUSTOMSRVREQUEST_H
